OI-wiki/OI-Wiki-export

.github/workflows/auto-release.yml
Be compatible with `workflow_dispatch`.
Fix id format (`-` => `_`).
=> CI: Build on every Sunday.

.github/workflows/auto-release.yml, .github/workflows/test-build.yml, oi-wiki-export/includes.tex, oi-wiki-export/oi-wiki-export.tex, oi-wiki-export/package-lock.json
=> add build test

.github/workflows/auto-release.yml, .github/workflows/test-build.yml, README.md
=> fix: add `-8bit` for minted code block represents tabs as ^^I

oi-wiki-export/oi-wiki-export.tex
=> fix: math font

remark-latex/lib/util.js
fix https://github.com/OI-wiki/OI-Wiki-export/issues/15
=> fix: nested list

README.md
=> docs:fix bug in compile

oi-wiki-export/oi-wiki-export.tex, remark-latex/lib/compiler.js, remark-latex/lib/util.js
1.将所有的外链添加到引用里
2.为引用中的链接添加二维码
后续：改一下二维码的格式
=> [WIP]Add qc in footnote

oi-wiki-export/oi-wiki-export.tex
Noto fonts in ci cause strange build failure, temporarily remove them.
=> fix: remote noto fonts

oi-wiki-export/index.js
- fix #27
- https://github.com/CCXXXI/OI-Wiki-export/runs/7313730860?check_suite_focus=true
=> fix: match all types

remark-latex/lib/compiler.js
https://github.com/OI-wiki/OI-wiki/pull/4760#issuecomment-1447541552
=> feat: line break before `\end{longtabu}`

oi-wiki-export/index.js, remark-latex/lib/compiler.js, remark-latex/lib/util.js
修复了图片路径开头为 "../" 时的 url 拼接错误问题
增加了针对 SVG 打印版本的优化
规范了导出时的信息显示
=> feat: svg printable version & bugfix

oi-wiki-export-typst/oi-wiki-export.typ, oi-wiki-export-typst/oi-wiki.typ, oi-wiki-export-typst/pymdownx-details.typ
the heading size is set according to https://www.sascha-frank.com/latex-font-size.html cc @megakite
=> adjust heading and details appearance

oi-wiki-export-typst/oi-wiki-export.typ
=> fix: wrong page numbers

oi-wiki-export-typst/index.js, oi-wiki-export-typst/oi-wiki.typ, oi-wiki-export-typst/package-lock.json, oi-wiki-export-typst/package.json
使用remark-tabbed插件为typst导出添加tabbed解析支持
=> feat(typst): support tabbed syntax

.github/workflows/auto-release.yml
ref: https://github.com/OI-wiki/OI-wiki/pull/5228
=> fix(latex): npm cache permission

.github/workflows/auto-release-typst.yml, .github/workflows/auto-release.yml, .github/workflows/test-build-typst.yml, .github/workflows/test-build.yml
=> improve ci

.github/workflows/auto-release-typst.yml, .github/workflows/auto-release.yml, .github/workflows/test-build-typst.yml
=> chore(ci): update workflows

.github/workflows/auto-release-typst.yml, .github/workflows/auto-release.yml
=> chore(ci): use cli to release

.github/workflows/auto-release.yml, .github/workflows/test-build.yml
Do the same as OI-Wiki/OI-Wiki#5857
=> fix(workflows/auto-release, test-build): change mirror to original site

oi-wiki-export/oi-wiki-export.tex
resolve https://github.com/OI-wiki/OI-wiki/actions/runs/11659060134/job/32459050703
=> feat(oi-wiki-export.tex): more predefined colors

remark-typst/.gitmodules
=> chore(typst): remove .gitmodules files

.github/workflows/auto-release-typst.yml, .github/workflows/test-build-typst.yml
Fix https://github.com/OI-wiki/OI-wiki/issues/6181
=> fix(workflow): update package lists first

oi-wiki-export/increase-mem-limit.py
fixes https://github.com/OI-wiki/OI-wiki/issues/6225
=> fix(oi-wiki-export): further increase mem limit
